version: '3'
services:
  api:
    build:
      context: ../..  # Build context points to the root of the project
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  app:
    build:
      context: ../..  # Build context points to the root of the project
      dockerfile: code/deployment/app/Dockerfile  # Specify the correct path to the Streamlit Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
